### ISSUE TITLE
Document changes done to Outbound

### ISSUE THREAD

**Issue by karntrehan** [samagra-comms/outbound#22]
Document changes done to 
- [ ] Setup
- [x] FCM Adapter
- [x] Hidden Fields

**Comment by chinmoy12c** [comment]
@karntrehan please review this PR:

https://github.com/samagra-comms/community/pull/28

**Comment by chinmoy12c** [comment]
Hey @karntrehan , I've updated the PR please go through some new comments.

**Comment by chinmoy12c** [comment]
Update the PR based on v2. @chinmoy12c
