### ISSUE TITLE
Merge release-v2.0.0 in Development and Deploy

### ISSUE THREAD

**Issue by pankajjangid05** [samagra-comms/outbound#31]
PR - https://github.com/samagra-comms/outbound/pull/30

**Comment by pankajjangid05** [comment]
- [x] Merge code in the development branch
- [x] Code deployed on stage server (CSM)
- [x] @chinmoy12c Please update here if health API's are working

**Comment by chinmoy12c** [comment]
Health API is working on outbound service.
