### ISSUE TITLE
Notification Pipeline

### ISSUE THREAD

**Issue by susheelvar** [samagra-comms/outbound#35]
**Parent Ticket**
Notification pipeline to be streamlined. 

**Current status**
User segment URL ([# of teachers with FCM](http://103.154.251.109:8070/segments/2/mentors/count)) (67473) > Number of users sent notificatons (32,548) from Kassandra > Notification received (PostHog) (12,306) > Notification opened (PostHog) (750)

#41 #42 #43 #44 #55

**Comment by pankajjangid05** [comment]
Tickets

- [ ] [#41](https://github.com/samagra-comms/orchestrator/issues/41)
- [x] [#42](https://github.com/samagra-comms/orchestrator/issues/42)
- [x] [#43](https://github.com/samagra-comms/orchestrator/issues/43)
- [ ] [#44](https://github.com/samagra-comms/orchestrator/issues/44)
- [x] [#55](https://github.com/samagra-comms/inbound/issues/55)

**Comment by pankajjangid05** [comment]
I have reopened the ticket again at https://github.com/samagra-comms/orchestrator/issues/41 due to Cassandra-related issues that we encountered yesterday. You can find more detailed information on the ticket.

**Comment by geeky-abhishek** [comment]
Axiom dashboard setup. Testing on setup will be done by 2nd June first half.

**Comment by geeky-abhishek** [comment]
update by @pankajjangid05

**Comment by pankajjangid05** [comment]
I am currently working on a batch notification-sending task. Yesterday, I encountered compatibility issues with certain dependencies. Today, my objective is to resolve these issues.
